# Generated by Django 5.2 on 2025-05-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('command_type', models.CharField(choices=[('show', 'Show Command'), ('config', 'Configuration Command'), ('validate', 'Validation Command')], max_length=20)),
                ('template', models.TextField(help_text='Use {{ variable }} syntax for variables')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Command Template',
                'verbose_name_plural': 'Command Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('device_type', models.CharField(choices=[('arista_eos', 'arista_eos'), ('cisco_ios', 'cisco_ios'), ('cisco_nxos', 'cisco_nxos'), ('generic', 'generic'), ('juniper', 'juniper'), ('juniper_junos', 'juniper_junos'), ('mikrotik_routeros', 'mikrotik_routeros'), ('mikrotik_switchos', 'mikrotik_switchos'), ('vyatta_vyos', 'vyatta_vyos'), ('vyos', 'vyos')], default='cisco_ios', max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('enable_password', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.IntegerField(default=22)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Network Device',
                'verbose_name_plural': 'Network Devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devices', models.ManyToManyField(related_name='groups', to='core.networkdevice')),
            ],
            options={
                'verbose_name': 'Device Group',
                'verbose_name_plural': 'Device Groups',
                'ordering': ['name'],
            },
        ),
    ]
