# Generated by Django 5.2 on 2025-05-14 09:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NornirCommandHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('output', models.TextField(blank=True)),
                ('status', models.CharField(default='success', max_length=20)),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nornir_command_history', to='core.networkdevice')),
            ],
            options={
                'verbose_name_plural': 'Nornir command histories',
                'ordering': ['-executed_at'],
            },
        ),
    ]
