# Generated by Django 5.2 on 2025-04-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmiko_tools', '0002_alter_networkdevice_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='device_type',
            field=models.CharField(choices=[('arista_eos', 'arista_eos'), ('cisco_ios', 'cisco_ios'), ('cisco_nxos', 'cisco_nxos'), ('generic', 'generic'), ('juniper', 'juniper'), ('juniper_junos', 'juniper_junos'), ('mikrotik_routeros', 'mikrotik_routeros'), ('mikrotik_switchos', 'mikrotik_switchos'), ('vyatta_vyos', 'vyatta_vyos'), ('vyos', 'vyos')], default='cisco_ios', max_length=100),
        ),
    ]
