# Generated by Django 5.2 on 2025-05-02 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netmiko_tools', '0003_alter_networkdevice_device_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandhistory',
            name='executed_by',
        ),
    ]
